In [2]:
import numpy as np

In [3]:
a = np.array([[0,1,2,3], [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
a.shape

(2, 4)

In [5]:
a[1, 3]

7

In [8]:
a[1, 2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [9]:
a[0]

array([0, 1, 2, 3])

In [10]:
a[1]

array([4, 5, 8, 7])

In [12]:
b = np.array([3, 5])
b

array([3, 5])